
export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'


// export const FIND_PRODUCT_BY_CATERGORY_REQUEST = 'FIND_PRODUCT_BY_CATERGORY_REQUEST'
// export const FIND_PRODUCT_BY_CATERGORY_SUCCESS = 'FIND_PRODUCT_BY_CATERGORY_SUCCESS'
// export const FIND_PRODUCT_BY_CATERGORY_FAILURE = 'FIND_PRODUCT_BY_CATERGORY_FAILURE'

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCTS_REQUEST'
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCTS_SUCCESS'
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCTS_FAILURE'


export const ADD_RATING = "ADD_RATING"

export const GET_HOME_PRODUCT = 'GET_HOME_PRODUCT'




